name: deploy website

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out
      - uses: actions/checkout@v2
      - name: vercel action 
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          working-directory: ./sub-directory

